% TRAINIDRIDGRADER
% Train and cross-validate a five-grade IDRiD diabetic-retinopathy grader.
%
% EXPERIMENT:
%   Augmentation-balanced training WITHOUT class weighting.
%
% Strategy:
%   - 3-fold stratified CV
%   - Inner 15%% split for early stopping
%   - Square-root class balancing by repeated training rows
%   - Random image augmentation applied to repeated rows
%   - NO class-weighted loss
%   - OOF probability collection
%   - OOF ordinal threshold fitting
%   - OOF grade-4 probability threshold fitting
%
% The official 103-image IDRiD test set is NEVER read here.
%
% Requires:
%   Deep Learning Toolbox
%   Image Processing Toolbox
%   Statistics and Machine Learning Toolbox
%   Parallel Computing Toolbox
%   CUDA-capable NVIDIA GPU
%
% Requires preprocessIDRiDImage.m on MATLAB path.

clear;
clc;

rng(42, 'twister');

% =========================================================================
% CONFIGURATION
% =========================================================================

numFolds = 5;

% =========================================================================
% GPU
% =========================================================================

if ~canUseGPU
    error([ ...
        'No CUDA GPU visible to MATLAB. Install Parallel Computing Toolbox ', ...
        'and a supported NVIDIA driver, then run gpuDeviceTable.']);
end

g = gpuDevice;

memGB = double(g.AvailableMemory) / 2^30;

fprintf( ...
    'GPU: %s | compute capability %s | %.2f GB free\n', ...
    string(g.Name), ...
    string(g.ComputeCapability), ...
    memGB);

% =========================================================================
% PATHS
% =========================================================================

projectDir = fileparts(mfilename('fullpath'));

dataRoot = fullfile( ...
    projectDir, ...
    'data', ...
    'B. Disease Grading', ...
    'B. Disease Grading');

archive = fullfile( ...
    projectDir, ...
    'data', ...
    'B. Disease Grading.zip');

trainImageDir = fullfile( ...
    dataRoot, ...
    '1. Original Images', ...
    'a. Training Set');

trainCsv = fullfile( ...
    dataRoot, ...
    '2. Groundtruths', ...
    'a. IDRiD_Disease Grading_Training Labels.csv');

modelDir = fullfile( ...
    projectDir, ...
    'models', ...
    'idrid_grade5');

% =========================================================================
% DATA CHECK
% =========================================================================

if ~isfolder(trainImageDir) || ...
        isempty(dir(fullfile(trainImageDir, '*.jpg')))

    if ~isfile(archive)
        error( ...
            'IDRiD archive not found: %s', ...
            archive);
    end

    unzip( ...
        archive, ...
        fullfile(projectDir, 'data', 'B. Disease Grading'));
end

if ~isfile(trainCsv)

    error( ...
        'Training labels not found: %s', ...
        trainCsv);

end

if ~isfolder(modelDir)
    mkdir(modelDir);
end

warning( ...
    'off', ...
    'MATLAB:table:ModifiedAndSavedVarnames');

% =========================================================================
% LOAD LABELS
% =========================================================================

T = readtable(trainCsv);

imageNames = string(T.ImageName);

rawGrades = double(T.RetinopathyGrade);

n = numel(imageNames);

classNames = string(0:4);

labels = categorical( ...
    string(rawGrades), ...
    classNames);

if any(isundefined(labels)) || n ~= 413

    error( ...
        'Expected 413 IDRiD training rows with grades in 0..4; found %d.', ...
        n);

end

filePaths = fullfile( ...
    trainImageDir, ...
    imageNames + ".jpg");

if any(~isfile(filePaths))

    missing = find(~isfile(filePaths), 1);

    error( ...
        'Image not found: %s', ...
        filePaths(missing));

end

% =========================================================================
% DATASET STATISTICS
% =========================================================================

counts = countcats(labels);

fprintf( ...
    '\nTraining counts, grades 0..4: %s\n', ...
    mat2str(counts'));

inputSize = [512 512 3];

% =========================================================================
% CACHE PREPROCESSED IMAGES
% =========================================================================

cachedPaths = ...
    cachePreprocessedImages( ...
        filePaths, ...
        imageNames, ...
        fullfile(modelDir, 'cache_512'), ...
        inputSize);

% =========================================================================
% BACKBONE
% =========================================================================

[~, backboneName] = ...
    buildGradingNetwork( ...
        inputSize, ...
        projectDir);

fprintf( ...
    'Backbone: %s\n', ...
    backboneName);

% =========================================================================
% FUNDUS AUGMENTATION
%
% Conservative geometric changes.
%
% We deliberately do NOT use reflection for this experiment.
% =========================================================================

augmenter = imageDataAugmenter( ...
    'RandRotation', [-10 10], ...
    'RandScale', [0.95 1.05], ...
    'RandXTranslation', [-8 8], ...
    'RandYTranslation', [-8 8]);

readCached = ...
    @(filename) readCachedNormalized(filename);

imds = imageDatastore( ...
    cachedPaths, ...
    'Labels', ...
        labels, ...
    'ReadFcn', ...
        readCached);

% =========================================================================
% CROSS-VALIDATION
% =========================================================================

cv = cvpartition( ...
    labels, ...
    'KFold', ...
    numFolds);

oofScores = ...
    nan(n, 5);

oofPredictions = ...
    nan(n, 1);

% Record the actual sampling used in each fold.
foldSamplingTargets = ...
    nan(numFolds, 5);

foldSamplingFactors = ...
    nan(numFolds, 5);

foldMetrics = table( ...
    'Size', ...
        [numFolds 5], ...
    'VariableTypes', ...
        {'double','double','double','double','double'}, ...
    'VariableNames', ...
        {'Fold', ...
         'Accuracy', ...
         'QWK', ...
         'MacroRecall', ...
         'Grade4Recall'});

miniBatch = ...
    pickMiniBatchSize( ...
        g.AvailableMemory);

fprintf( ...
    '\nInitial mini-batch size: %d\n', ...
    miniBatch);

% =========================================================================
% TRAIN FOLDS
% =========================================================================

for fold = 1:numFolds

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('Fold %d / %d\n', fold, numFolds);
    fprintf('============================================================\n');

    % ---------------------------------------------------------------------
    % Outer fold
    % ---------------------------------------------------------------------

    trainIdx = ...
        training(cv, fold);

    valIdx = ...
        test(cv, fold);

    foldTrainingRows = ...
        find(trainIdx);

    % ---------------------------------------------------------------------
    % Inner 15%% validation split
    % ---------------------------------------------------------------------

    inner = cvpartition( ...
        labels(trainIdx), ...
        'HoldOut', ...
        0.15);

    innerTrainRows = ...
        foldTrainingRows( ...
            training(inner));

    earlyStopRows = ...
        foldTrainingRows( ...
            test(inner));

    % ---------------------------------------------------------------------
    % Actual inner-training class counts
    % ---------------------------------------------------------------------

    trainGrades = ...
        rawGrades(innerTrainRows);

    foldCounts = ...
        accumarray( ...
            trainGrades + 1, ...
            1, ...
            [5 1], ...
            @sum, ...
            0);

    if any(foldCounts == 0)

        error( ...
            'Fold %d contains a class with zero training samples.', ...
            fold);

    end

    % ---------------------------------------------------------------------
    % SQUARE-ROOT BALANCING
    %
    % target = sqrt(count * maximumCount)
    %
    % This gives moderate augmentation-based balancing.
    %
    % Example:
    %
    % count = [77 11 77 42 28]
    %
    % target ~= [77 29 77 57 46]
    %
    % This is substantially less aggressive than forcing every class
    % to the largest class.
    % ---------------------------------------------------------------------

    maxCount = ...
        max(foldCounts);

    targetCounts = ...
        round( ...
            sqrt( ...
                double(foldCounts) * ...
                double(maxCount)));

    targetCounts = ...
        max( ...
            targetCounts, ...
            foldCounts);

    samplingFactors = ...
        targetCounts ./ ...
        foldCounts;

    foldSamplingTargets(fold, :) = ...
        targetCounts(:)';

    foldSamplingFactors(fold, :) = ...
        samplingFactors(:)';

    fprintf( ...
        'Fold %d original counts, grades 0..4: %s\n', ...
        fold, ...
        mat2str(foldCounts'));

    fprintf( ...
        'Fold %d augmented targets, grades 0..4: %s\n', ...
        fold, ...
        mat2str(targetCounts'));

    fprintf( ...
        'Fold %d sampling factors: %s\n', ...
        fold, ...
        mat2str(samplingFactors, 2));

    % ---------------------------------------------------------------------
    % Build repeated-row training set.
    %
    % IMPORTANT:
    % These are row repetitions, not saved duplicate images.
    %
    % augmentedImageDatastore will apply random transformations when
    % each occurrence is read.
    % ---------------------------------------------------------------------

    balancedRows = ...
        balanceTrainingRows( ...
            innerTrainRows, ...
            rawGrades, ...
            targetCounts);

    fprintf( ...
        'Training rows after square-root balancing: %d\n', ...
        numel(balancedRows));

    % ---------------------------------------------------------------------
    % Training datastore
    % ---------------------------------------------------------------------

    trainDS = imageDatastore( ...
        cachedPaths(balancedRows), ...
        'Labels', ...
            labels(balancedRows), ...
        'ReadFcn', ...
            readCached);

    trainDS.ReadSize = ...
        miniBatch;

    % ---------------------------------------------------------------------
    % Early stopping datastore
    % ---------------------------------------------------------------------

    earlyStopDS = ...
        subset( ...
            imds, ...
            earlyStopRows);

    valDS = ...
        subset( ...
            imds, ...
            find(valIdx));

    % ---------------------------------------------------------------------
    % Augmented training datastore
    %
    % Every repeated minority example receives randomized transformations
    % when read.
    % ---------------------------------------------------------------------

    trainAug = ...
        augmentedImageDatastore( ...
            inputSize(1:2), ...
            trainDS, ...
            'DataAugmentation', ...
            augmenter);

    trainAug.MiniBatchSize = ...
        miniBatch;

    earlyStopAug = ...
        augmentedImageDatastore( ...
            inputSize(1:2), ...
            earlyStopDS);

    earlyStopAug.MiniBatchSize = ...
        miniBatch;

    stepsPerEpoch = ...
        max( ...
            1, ...
            ceil( ...
                numel(balancedRows) / ...
                miniBatch));

    % ---------------------------------------------------------------------
    % Checkpoint directory
    % ---------------------------------------------------------------------

    ckptDir = ...
        fullfile( ...
            modelDir, ...
            sprintf( ...
                'checkpoints_fold-%d', ...
                fold));

    if ~isfolder(ckptDir)
        mkdir(ckptDir);
    end

    % ---------------------------------------------------------------------
    % IMPORTANT:
    % NO CLASS WEIGHTS
    %
    % This experiment tests augmentation-based balancing by itself.
    % ---------------------------------------------------------------------

    lossFcn = ...
        'crossentropy';

    % ---------------------------------------------------------------------
    % TRAIN
    % ---------------------------------------------------------------------

    trained = false;

    batchTry = ...
        miniBatch;

    while ~trained

        net = ...
            buildGradingNetwork( ...
                inputSize, ...
                projectDir);

        options = ...
            makeGpuTrainOptions( ...
                batchTry, ...
                earlyStopAug, ...
                stepsPerEpoch, ...
                ckptDir);

        fprintf( ...
            'Training on GPU, MiniBatchSize %d, ~%d steps/epoch\n', ...
            batchTry, ...
            max( ...
                1, ...
                ceil( ...
                    numel(balancedRows) / ...
                    batchTry)));

        try

            net = ...
                trainnet( ...
                    trainAug, ...
                    net, ...
                    lossFcn, ...
                    options);

            trained = true;

            miniBatch = ...
                batchTry;

        catch err

            if batchTry > 2 && ...
                    isGpuMemoryError(err)

                nextBatch = ...
                    max( ...
                        2, ...
                        floor( ...
                            batchTry / 2));

                fprintf( ...
                    ['GPU out of memory at batch %d. ', ...
                     'Retrying with %d.\n'], ...
                    batchTry, ...
                    nextBatch);

                batchTry = ...
                    nextBatch;

                trainAug.MiniBatchSize = ...
                    batchTry;

                earlyStopAug.MiniBatchSize = ...
                    batchTry;

                reset(gpuDevice);

            else

                rethrow(err);

            end
        end
    end

    % ---------------------------------------------------------------------
    % Score outer validation fold
    % ---------------------------------------------------------------------

    scores = ...
        scoreNetwork( ...
            net, ...
            valDS, ...
            miniBatch);

    % ---------------------------------------------------------------------
    % Argmax prediction
    % ---------------------------------------------------------------------

    [~, scoreIndex] = ...
        max( ...
            scores, ...
            [], ...
            2);

    predLabels = ...
        categorical( ...
            string(scoreIndex - 1), ...
            classNames);

    truth = ...
        rawGrades(valIdx);

    predicted = ...
        str2double( ...
            string(predLabels));

    % ---------------------------------------------------------------------
    % Store OOF predictions
    % ---------------------------------------------------------------------

    oofScores(valIdx, :) = ...
        scores;

    oofPredictions(valIdx) = ...
        predicted;

    % ---------------------------------------------------------------------
    % Fold metrics
    % ---------------------------------------------------------------------

    metrics = ...
        gradeMetrics( ...
            truth, ...
            predicted);

    foldMetrics{fold, :} = ...
        [ ...
            fold, ...
            metrics.accuracy, ...
            metrics.qwk, ...
            metrics.macroRecall, ...
            metrics.grade4Recall];

    fprintf( ...
        ['Fold %d | accuracy %.3f | QWK %.3f | ', ...
         'macro recall %.3f | grade-4 recall %.3f\n'], ...
        fold, ...
        metrics.accuracy, ...
        metrics.qwk, ...
        metrics.macroRecall, ...
        metrics.grade4Recall);

    % ---------------------------------------------------------------------
    % Save fold model
    % ---------------------------------------------------------------------

    foldModelPath = ...
        fullfile( ...
            modelDir, ...
            sprintf( ...
                'fold-%d.mat', ...
                fold));

    save( ...
        foldModelPath, ...
        'net', ...
        'inputSize', ...
        'classNames', ...
        'backboneName', ...
        'fold', ...
        'foldCounts', ...
        'targetCounts', ...
        'samplingFactors', ...
        '-v7.3');

    fprintf( ...
        'Saved %s\n', ...
        foldModelPath);

    clear net;

end

% =========================================================================
% VERIFY OOF COMPLETENESS
% =========================================================================

if any(isnan(oofScores(:)))

    error( ...
        'OOF scores contain NaN values. Not every sample was evaluated.');

end

if any(isnan(oofPredictions))

    error( ...
        'OOF predictions contain NaN values. Not every sample was evaluated.');

end

% =========================================================================
% ARGMAX OOF
% =========================================================================

oofMetrics = ...
    gradeMetrics( ...
        rawGrades, ...
        oofPredictions);

% =========================================================================
% EXPECTED GRADE
% =========================================================================

expectedGrades = ...
    oofScores * (0:4)';

% =========================================================================
% ORDINAL THRESHOLDS
% =========================================================================

thresholds = ...
    fitGradeThresholds( ...
        expectedGrades, ...
        rawGrades);

ordinalPredictions = ...
    decodeGrades( ...
        expectedGrades, ...
        thresholds);

ordinalMetrics = ...
    gradeMetrics( ...
        rawGrades, ...
        ordinalPredictions);

% =========================================================================
% HYBRID GRADE-4 THRESHOLD
% =========================================================================

[
    grade4ProbThreshold, ...
    hybridPredictions, ...
    hybridMetrics] = ...
    fitGrade4ProbThreshold( ...
        oofScores, ...
        expectedGrades, ...
        rawGrades, ...
        thresholds);

% =========================================================================
% HYBRID CONFUSION
% =========================================================================

confusion = ...
    confusionmat( ...
        rawGrades, ...
        hybridPredictions, ...
        'Order', ...
        0:4);

% =========================================================================
% DISPLAY RESULTS
% =========================================================================

disp(' ');
disp('============================================================');
disp('OUT-OF-FOLD RESULTS');
disp('============================================================');

fprintf( ...
    ['Argmax OOF   : accuracy %.3f | QWK %.3f | ', ...
     'macro recall %.3f | grade-4 recall %.3f\n'], ...
    oofMetrics.accuracy, ...
    oofMetrics.qwk, ...
    oofMetrics.macroRecall, ...
    oofMetrics.grade4Recall);

fprintf( ...
    ['Ordinal OOF  : accuracy %.3f | QWK %.3f | ', ...
     'macro recall %.3f | grade-4 recall %.3f\n'], ...
    ordinalMetrics.accuracy, ...
    ordinalMetrics.qwk, ...
    ordinalMetrics.macroRecall, ...
    ordinalMetrics.grade4Recall);

fprintf( ...
    ['Hybrid OOF   : accuracy %.3f | QWK %.3f | ', ...
     'macro recall %.3f | grade-4 recall %.3f\n'], ...
    hybridMetrics.accuracy, ...
    hybridMetrics.qwk, ...
    hybridMetrics.macroRecall, ...
    hybridMetrics.grade4Recall);

fprintf( ...
    ['Hybrid OOF   : macro F1 %.3f | grade-4 precision %.3f | ', ...
     'grade-4 F1 %.3f | referable sensitivity %.3f\n'], ...
    hybridMetrics.macroF1, ...
    hybridMetrics.grade4Precision, ...
    hybridMetrics.grade4F1, ...
    hybridMetrics.referableSensitivity);

fprintf( ...
    '\nFitted ordinal thresholds: %s\n', ...
    mat2str(thresholds, 4));

fprintf( ...
    'Fitted grade-4 probability threshold: %.4f\n', ...
    grade4ProbThreshold);

disp(' ');
disp('Hybrid OOF confusion matrix:');

disp( ...
    array2table( ...
        confusion, ...
        'VariableNames', ...
            "Pred_" + classNames, ...
        'RowNames', ...
            "True_" + classNames));

% =========================================================================
% SAVE FOLD METRICS
% =========================================================================

writetable( ...
    foldMetrics, ...
    fullfile( ...
        modelDir, ...
        'fold_metrics.csv'));

% =========================================================================
% SAVE CV ARTIFACT
% =========================================================================

save( ...
    fullfile( ...
        modelDir, ...
        'cross_validation.mat'), ...
    'oofScores', ...
    'oofPredictions', ...
    'hybridPredictions', ...
    'ordinalPredictions', ...
    'expectedGrades', ...
    'thresholds', ...
    'grade4ProbThreshold', ...
    'rawGrades', ...
    'confusion', ...
    'oofMetrics', ...
    'ordinalMetrics', ...
    'hybridMetrics', ...
    'foldMetrics', ...
    'foldSamplingTargets', ...
    'foldSamplingFactors', ...
    'inputSize', ...
    'classNames', ...
    'backboneName');

fprintf('\n');
fprintf('============================================================\n');
fprintf('TRAINING COMPLETE\n');
fprintf('============================================================\n');

fprintf( ...
    'Saved %d fold models under:\n%s\n', ...
    numFolds, ...
    modelDir);

fprintf( ...
    'Saved grade-4 probability threshold: %.4f\n', ...
    grade4ProbThreshold);

fprintf( ...
    'Saved cross_validation.mat with OOF scores and frozen decoder.\n');

% =========================================================================
% LOCAL FUNCTIONS
% =========================================================================

function [net, backboneName] = ...
    buildGradingNetwork( ...
        inputSize, ...
        projectDir)

net = [];
backboneName = '';

% -------------------------------------------------------------------------
% MATLAB pretrained networks
% -------------------------------------------------------------------------

if exist('imagePretrainedNetwork', 'file') == 2

    modelNames = ...
        ["efficientnetb0", "resnet50"];

    for i = 1:numel(modelNames)

        modelName = ...
            modelNames(i);

        try

            net = ...
                imagePretrainedNetwork( ...
                    modelName, ...
                    'NumClasses', ...
                    5);

            net = ...
                replaceImageInput( ...
                    net, ...
                    inputSize);

            backboneName = ...
                char(modelName);

            return;

        catch err

            fprintf( ...
                '%s not used: %s\n', ...
                modelName, ...
                err.message);

            net = [];

        end
    end
end

% -------------------------------------------------------------------------
% ONNX fallback
% -------------------------------------------------------------------------

onnxPath = ...
    fullfile( ...
        projectDir, ...
        'data', ...
        'efficientnet_b0_regression_512px.onnx');

if ~isfile(onnxPath)

    error([ ...
        'Install the EfficientNet-B0 or ResNet-50 support package, ', ...
        'or place efficientnet_b0_regression_512px.onnx under data/.']);

end

baseNet = ...
    importNetworkFromONNX( ...
        onnxPath);

lgraph = ...
    layerGraph(baseNet);

head = ...
    fullyConnectedLayer( ...
        5, ...
        'Name', ...
            'grade_head', ...
        'WeightLearnRateFactor', ...
            10, ...
        'BiasLearnRateFactor', ...
            10, ...
        'WeightsInitializer', ...
            'he');

lgraph = ...
    replaceLayer( ...
        lgraph, ...
        'x_backbone_classifie', ...
        head);

lgraph = ...
    addLayers( ...
        lgraph, ...
        softmaxLayer( ...
            'Name', ...
                'grade_softmax'));

lgraph = ...
    connectLayers( ...
        lgraph, ...
        'grade_head', ...
        'grade_softmax');

net = ...
    dlnetwork(lgraph);

backboneName = ...
    'efficientnet_b0_onnx';

end

% =========================================================================

function net = ...
    replaceImageInput( ...
        net, ...
        inputSize)

lgraph = ...
    layerGraph(net);

layers = ...
    lgraph.Layers;

isInput = ...
    arrayfun( ...
        @(layer) ...
            isa( ...
                layer, ...
                'nnet.cnn.layer.ImageInputLayer'), ...
        layers);

if ~any(isInput)

    error( ...
        'No image input layer found.');

end

oldLayer = ...
    layers(find(isInput, 1));

newLayer = ...
    imageInputLayer( ...
        inputSize, ...
        'Name', ...
            oldLayer.Name, ...
        'Normalization', ...
            'none');

lgraph = ...
    replaceLayer( ...
        lgraph, ...
        oldLayer.Name, ...
        newLayer);

net = ...
    dlnetwork(lgraph);

end

% =========================================================================

function options = ...
    makeGpuTrainOptions( ...
        miniBatch, ...
        valData, ...
        stepsPerEpoch, ...
        ckptDir)

common = { ...
    'InitialLearnRate', ...
        1e-4, ...
    'MiniBatchSize', ...
        miniBatch, ...
    'MaxEpochs', ...
        10, ...
    'Shuffle', ...
        'every-epoch', ...
    'ValidationData', ...
        valData, ...
    'ValidationFrequency', ...
        stepsPerEpoch, ...
    'ValidationPatience', ...
        5, ...
    'ExecutionEnvironment', ...
        'gpu', ...
    'Verbose', ...
        true, ...
    'VerboseFrequency', ...
        5, ...
    'Plots', ...
        'none', ...
    'OutputNetwork', ...
        'best-validation-loss', ...
    'CheckpointPath', ...
        ckptDir, ...
    'CheckpointFrequency', ...
        1};

try

    options = ...
        trainingOptions( ...
            'adam', ...
            common{:}, ...
            'CheckpointFrequencyUnit', ...
                'epoch', ...
            'DispatchInBackground', ...
                true);

    return;

catch
end

try

    options = ...
        trainingOptions( ...
            'adam', ...
            common{:}, ...
            'DispatchInBackground', ...
                true);

    return;

catch
end

options = ...
    trainingOptions( ...
        'adam', ...
        common{:});

end

% =========================================================================

function miniBatch = ...
    pickMiniBatchSize( ...
        availableBytes)

gb = ...
    double(availableBytes) / 2^30;

if gb >= 8

    miniBatch = 16;

elseif gb >= 5

    miniBatch = 8;

elseif gb >= 3

    miniBatch = 4;

else

    miniBatch = 2;

end

end

% =========================================================================

function tf = ...
    isGpuMemoryError( ...
        err)

msg = lower( ...
    string(err.message) + ...
    " " + ...
    string(err.identifier));

tf = ...
    contains(msg, "out of memory") || ...
    contains(msg, "oom") || ...
    ( ...
        contains(msg, "gpu") && ...
        contains(msg, "memory"));

end

% =========================================================================

function cachedPaths = ...
    cachePreprocessedImages( ...
        filePaths, ...
        imageNames, ...
        cacheDir, ...
        inputSize)

if ~isfolder(cacheDir)
    mkdir(cacheDir);
end

cachedPaths = ...
    strings(size(filePaths));

fprintf( ...
    'Caching 512 px training images under %s\n', ...
    cacheDir);

for i = 1:numel(filePaths)

    outFile = ...
        fullfile( ...
            cacheDir, ...
            imageNames(i) + ".png");

    cachedPaths(i) = ...
        outFile;

    if isfile(outFile)
        continue;
    end

    rgb = ...
        preprocessIDRiDImage( ...
            filePaths(i), ...
            inputSize, ...
            false);

    imwrite( ...
        rgb, ...
        outFile);

    if mod(i, 25) == 0 || ...
            i == numel(filePaths)

        fprintf( ...
            '  cached %d / %d\n', ...
            i, ...
            numel(filePaths));

    end
end

end

% =========================================================================

function I = ...
    readCachedNormalized( ...
        filename)

pixels = ...
    im2single( ...
        imread(filename));

meanRGB = ...
    reshape( ...
        single([0.485 0.456 0.406]), ...
        1, 1, 3);

stdRGB = ...
    reshape( ...
        single([0.229 0.224 0.225]), ...
        1, 1, 3);

I = ...
    (pixels - meanRGB) ./ stdRGB;

end

% =========================================================================

function rows = ...
    balanceTrainingRows( ...
        sourceRows, ...
        grades, ...
        targetCounts)

% Create a moderately balanced training-row list.
%
% Each class is sampled with replacement until it reaches its target.
%
% The repeated rows are later passed through augmentedImageDatastore,
% so repeated observations receive randomized geometric transformations.

foldGrades = ...
    grades(sourceRows);

rows = ...
    zeros(0, 1);

for grade = 0:4

    classRows = ...
        sourceRows( ...
            foldGrades == grade);

    if isempty(classRows)

        error( ...
            'Cannot sample grade %d because it has no examples.', ...
            grade);

    end

    targetCount = ...
        targetCounts(grade + 1);

    selected = ...
        classRows( ...
            randsample( ...
                numel(classRows), ...
                targetCount, ...
                true));

    rows = ...
        [rows; selected]; %#ok<AGROW>

end

% Shuffle the repeated rows.
rows = ...
    rows( ...
        randperm( ...
            numel(rows)));

end

% =========================================================================

function scores = ...
    scoreNetwork( ...
        net, ...
        ds, ...
        miniBatch)

numImages = ...
    numel(ds.Files);

scores = ...
    zeros( ...
        numImages, ...
        5, ...
        'single');

sample = ...
    single( ...
        readimage( ...
            ds, ...
            1));

H = ...
    size(sample, 1);

W = ...
    size(sample, 2);

hasSoftmax = ...
    any( ...
        arrayfun( ...
            @(l) ...
                isa( ...
                    l, ...
                    'nnet.cnn.layer.SoftmaxLayer'), ...
            net.Layers));

useSoftmax = ...
    ~hasSoftmax;

for startIdx = ...
        1:miniBatch:numImages

    stopIdx = ...
        min( ...
            startIdx + miniBatch - 1, ...
            numImages);

    nb = ...
        stopIdx - startIdx + 1;

    batch = ...
        zeros( ...
            H, ...
            W, ...
            3, ...
            nb, ...
            'single');

    for j = 1:nb

        batch(:, :, :, j) = ...
            single( ...
                readimage( ...
                    ds, ...
                    startIdx + j - 1));

    end

    X = ...
        dlarray( ...
            gpuArray(batch), ...
            'SSCB');

    out = ...
        predict( ...
            net, ...
            X);

    if useSoftmax
        out = softmax(out);
    end

    P = ...
        reshape( ...
            gather( ...
                extractdata(out)), ...
            5, []);

    scores( ...
        startIdx:stopIdx, :) = ...
        P';

end

end

% =========================================================================

function m = ...
    gradeMetrics( ...
        truth, ...
        predicted)

valid = ...
    isfinite(predicted);

truth = ...
    truth(valid);

predicted = ...
    predicted(valid);

cm = ...
    confusionmat( ...
        truth, ...
        predicted, ...
        'Order', ...
        0:4);

recall = ...
    diag(cm) ./ ...
    max( ...
        sum(cm, 2), ...
        1);

precision = ...
    diag(cm) ./ ...
    max( ...
        sum(cm, 1)', ...
        1);

f1 = ...
    2 .* precision .* recall ./ ...
    max( ...
        precision + recall, ...
        eps);

n = ...
    sum(cm(:));

[r, c] = ...
    ndgrid( ...
        0:4, ...
        0:4);

w = ...
    (r - c).^2 / 16;

observed = ...
    sum( ...
        w(:) .* cm(:)) / ...
    max(n, 1);

expectedCounts = ...
    sum(cm, 2) * ...
    sum(cm, 1) / ...
    max(n, 1);

expected = ...
    sum( ...
        w(:) .* expectedCounts(:)) / ...
    max(n, 1);

m.accuracy = ...
    sum(diag(cm)) / ...
    max(n, 1);

m.qwk = ...
    1 - observed / ...
    max(expected, eps);

m.macroRecall = ...
    mean(recall);

m.macroF1 = ...
    mean(f1);

m.grade4Recall = ...
    recall(5);

m.grade4Precision = ...
    precision(5);

m.grade4F1 = ...
    f1(5);

end

% =========================================================================

function thresholds = ...
    fitGradeThresholds( ...
        expectedGrades, ...
        truth)

% Fit ordinal thresholds ONLY on OOF predictions.

thresholds = ...
    0.5:1:3.5;

basePred = ...
    decodeGrades( ...
        expectedGrades, ...
        thresholds);

best = ...
    gradeMetrics( ...
        truth, ...
        basePred).qwk;

for pass = 1:5

    changed = false;

    for j = 1:4

        lo = ...
            -0.25;

        hi = ...
            4.25;

        if j > 1

            lo = ...
                thresholds(j - 1) + ...
                0.02;

        end

        if j < 4

            hi = ...
                thresholds(j + 1) - ...
                0.02;

        end

        candidates = ...
            linspace( ...
                lo, ...
                hi, ...
                61);

        for candidate = candidates

            trial = ...
                thresholds;

            trial(j) = ...
                candidate;

            trialPred = ...
                decodeGrades( ...
                    expectedGrades, ...
                    trial);

            score = ...
                gradeMetrics( ...
                    truth, ...
                    trialPred).qwk;

            if score > best

                best = ...
                    score;

                thresholds = ...
                    trial;

                changed = true;

            end
        end
    end

    if ~changed
        break;
    end
end

end

% =========================================================================

function predicted = ...
    decodeGrades( ...
        expectedGrades, ...
        thresholds)

predicted = ...
    zeros(size(expectedGrades));

for threshold = thresholds

    predicted = ...
        predicted + ...
        (expectedGrades > threshold);

end

end

% =========================================================================

function [ ...
        bestThreshold, ...
        bestPred, ...
        bestMetrics] = ...
    fitGrade4ProbThreshold( ...
        scores, ...
        expectedGrades, ...
        truth, ...
        thresholds)

% Fit grade-4 probability threshold ONLY on OOF predictions.
%
% Grade 4 override:
%   argmax == 4
%   OR
%   P(grade 4) >= threshold
%
% Objective:
%   30%% QWK
%   20%% referable sensitivity
%   20%% grade-4 F1
%   30%% macro F1

[~, idx] = ...
    max( ...
        scores, ...
        [], ...
        2);

argmaxPred = ...
    idx - 1;

ordinalPred = ...
    decodeGrades( ...
        expectedGrades, ...
        thresholds);

candidateThresholds = ...
    0:0.005:1;

bestScore = ...
    -Inf;

bestThreshold = ...
    0.5;

bestPred = ...
    ordinalPred;

bestMetrics = ...
    gradeMetrics( ...
        truth, ...
        ordinalPred);

bestMetrics.referableSensitivity = ...
    calculateReferableSensitivity( ...
        truth, ...
        ordinalPred);

bestMetrics.compositeScore = ...
    -Inf;

for t = candidateThresholds

    pred = ...
        ordinalPred;

    forceGrade4 = ...
        (argmaxPred == 4) | ...
        (scores(:,5) >= t);

    pred(forceGrade4) = ...
        4;

    m = ...
        gradeMetrics( ...
            truth, ...
            pred);

    cm = ...
        confusionmat( ...
            truth, ...
            pred, ...
            'Order', ...
            0:4);

    % -------------------------------------------------------------
    % Grade-4 metrics
    % -------------------------------------------------------------

    grade4TP = ...
        cm(5,5);

    grade4FN = ...
        sum(cm(5,1:4));

    grade4FP = ...
        sum(cm(1:4,5));

    grade4Recall = ...
        grade4TP / ...
        max( ...
            grade4TP + grade4FN, ...
            1);

    grade4Precision = ...
        grade4TP / ...
        max( ...
            grade4TP + grade4FP, ...
            1);

    grade4F1 = ...
        2 * grade4Precision * ...
        grade4Recall / ...
        max( ...
            grade4Precision + ...
            grade4Recall, ...
            eps);

    % -------------------------------------------------------------
    % Referable sensitivity
    % -------------------------------------------------------------

    refSens = ...
        calculateReferableSensitivity( ...
            truth, ...
            pred);

    % -------------------------------------------------------------
    % Composite score
    % -------------------------------------------------------------

    composite = ...
          0.30 * m.qwk ...
        + 0.20 * refSens ...
        + 0.20 * grade4F1 ...
        + 0.30 * m.macroF1;

    if composite > bestScore + 1e-12 || ...
            ( ...
                abs(composite - bestScore) <= 1e-12 && ...
                t > bestThreshold)

        bestScore = ...
            composite;

        bestThreshold = ...
            t;

        bestPred = ...
            pred;

        bestMetrics = ...
            m;

        bestMetrics.grade4Recall = ...
            grade4Recall;

        bestMetrics.grade4Precision = ...
            grade4Precision;

        bestMetrics.grade4F1 = ...
            grade4F1;

        bestMetrics.referableSensitivity = ...
            refSens;

        bestMetrics.compositeScore = ...
            composite;

    end
end

end

% =========================================================================

function sensitivity = ...
    calculateReferableSensitivity( ...
        truth, ...
        predicted)

trueReferable = ...
    truth >= 2;

predReferable = ...
    predicted >= 2;

TP = ...
    sum( ...
        trueReferable & ...
        predReferable);

FN = ...
    sum( ...
        trueReferable & ...
        ~predReferable);

sensitivity = ...
    TP / ...
    max( ...
        TP + FN, ...
        1);

end